name: logmate
description: "A Flutter package for LogMate"
version: 0.0.1-beta
#homepage: ''
repository: https://github.com/bhoominn/logmate_flutter_package

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

flutter:
  uses-material-design: true
