name: logmate
description: "LogMate is a Flutter package that helps developers track and monitor logs remotely from their apps. It's perfect for debugging, monitoring, or error reporting."
version: 0.0.6-beta
homepage: https://github.com/bhoominn/logmate_flutter_package
repository: https://github.com/bhoominn/logmate_flutter_package
issue_tracker: https://github.com/bhoominn/logmate_flutter_package/issues
funding:
  - https://www.github.com/sponsors/bhoominn

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

flutter:
  uses-material-design: true

topics:
  - remotelog
  - log
  - logging